### ISSUE TITLE
What's the best lunch place around Kamppi?

### ISSUE THREAD

**Issue by justinwoo** [staltz/ama#10]
My friend and I have a hard time finding somewhere to go for lunch almost every day. Do you know of a good place to go around Kamppi, Helsinki?

**Comment by staltz** [comment]
![san-pedro-tex-mex-ravintola-kauppakeskus-kamppi-helsinki](https://cloud.githubusercontent.com/assets/90512/20392883/72d3db98-ace2-11e6-8f8d-30ac91fdd146.jpg)

Particularly the burrito with cheddar cheese and cucumbers.

**Comment by justinwoo** [comment]
u r the devil, helvetin saatana
