### ISSUE TITLE
What's your definition of a successful career?

### ISSUE THREAD

**Issue by tusharmath** [staltz/ama#11]
Is it making money or fame? How much have you accomplished so far?

**Comment by staltz** [comment]
My personal definition of a successful career is reaching achievements that you won't ashamed of later in your life. Do things that make your future self proud of 20 years from now.

> Is it making money or fame?

Making a lot of money is not my thing. I actually don't know how to spend money. Like I really don't know where I would put it. (cars? no way. games? a few are enough for me. fancy computers? already got one, and one is enough. traveling? I don't like traveling. fancy house? I'm fine with my few square meters. fancy clothes? I hate shopping for clothes. where do people honestly put money? luxury yachts?) So what often happens is that I save up money and then spend some months without working or something like that.

Fame actually is quite bad thing to gather. It's good for some things, you can leverage it, you can get a message across a lot easier to a larger audience. But it drains energy, you lose some privacy as people tend to judge you more easily when they feel entitled for whatever reason. Fame makes you sometimes too comfortable, too self confident in saying or doing whatever as there will usually be supporters. If you picture followers as a normal distribution (see footnote), where the x-axis is `hates-you --- loves-you`, the more famous you are, the more there are people who: (1) absolutely love you, (2) absolutely hate you, even though the majority of people in that bell curve have mild judgements of you. So gathering fame is gathering more of (2) people and that may be quite hard to handle. I don't think humans have evolved for handling mass attention. Humans are sort of optimized for tribe-sized communities of about 40~500 people. So, don't seek for fame. I wish I could just put a maximum limit of 6k followers in twitter. :)

So, for me, in my opinion, it's about doing things I will be proud about. And these things may not be related to work at all. Or they may be. One thing I am immensely happy to have achieved is a prog-metal album I recorded all by myself when I was 18 years old. It took me 2 years, lots of passion and lots of failed attempts. [This thing](https://soundcloud.com/andrestaltz/sets/o-vazio-tem-um-nome). It didn't bring any money. It didn't bring any fame. And many years after, I'm still very proud of it. 

You could say that's not related to "career". Fair enough. On the other hand, I've noticed that if you simply do the things you love no matter what, there's a good probability that eventually the business model will find. Sort of like the [Shakespeare/monkey theorem](https://en.wikipedia.org/wiki/Infinite_monkey_theorem).

I want to do more of that type of stuff in my life. Things that make me think life was worth living.

---

Footnote about normal distribution of followers:

![photo_2016-11-17_17-27-49](https://cloud.githubusercontent.com/assets/90512/20395367/5a4199cc-aceb-11e6-8c22-3fbe7dd78e5f.jpg)

![photo_2016-11-17_17-27-49 2](https://cloud.githubusercontent.com/assets/90512/20395374/5eef72b4-aceb-11e6-89fb-b356e2145dc1.jpg)

![photo_2016-11-17_17-27-50](https://cloud.githubusercontent.com/assets/90512/20395380/62aedc6e-aceb-11e6-8224-f6afbcc9eaf1.jpg)

![photo_2016-11-17_17-27-51](https://cloud.githubusercontent.com/assets/90512/20395384/654c9506-aceb-11e6-8eb6-20d03704c43d.jpg)

![photo_2016-11-17_17-27-52](https://cloud.githubusercontent.com/assets/90512/20395392/68816d96-aceb-11e6-9436-9be81e883c93.jpg)

![photo_2016-11-17_17-27-53](https://cloud.githubusercontent.com/assets/90512/20395395/6bc9122e-aceb-11e6-9817-36f886e82317.jpg)

**Comment by tusharmath** [comment]
Missed part 2 of the question. 

> How much have you accomplished so far?
