### ISSUE TITLE
rxjs + ramda + typescript

### ISSUE THREAD

**Issue by marcusradell** [staltz/ama#12]
Hi! So glad to see you doing an AMA. I've promised myself not to write too often ;-)
I've been inspired by cycle.js, and also by FP via Brian Lonsdorf.
You also wrote that Haskell is the only language to write real backends in, so I've tried to write Haskell-ish code in JS.

The trouble is that currying/partially applying and typescript doesn't seem to match well.
Then again, the need for something like ramda to curry or compose reactive code might not arise as much.

Given a reactive tool, what mix of functional tools and types-enabling tools would give the most bang for the buck for a typical large admin-GUI based on cycle.js? Is there some combination too quirky right now that it's worth skipping?

And big thanks for the awesome coding philosophies!

**Comment by staltz** [comment]
Hi Marcus!

TypeScript so far gives the best return on investments for functional programming. Writing code being aware of types is super important. 

I know some people like Ramda, and that's a good thing. About currying, however, I think it's a nice to have feature, that's not absolutely essential for functional programming in JavaScript. Most of the time I do manual currying. You can still get the job done. E.g.:

```js
function makeAdd(x: number) {
  return add(y: number): number {
    return x + y;
  }
}
```

I know it makes code bit more verbose, but it's quite explicit and other JavaScript programmers can understand it.

I'm not downplaying the value of automatic currying like in Haskell, PureScript, Elm. It's valuable. I'm just saying that for JavaScript and TypeScript, it is not absolutely essential.

Then, it would be nice to use immutable.js, but it doesn't play well with TypeScript. So just keep that in mind, but I still recommend both typescript and immutable.js. They have different roles, but both of them improve the functional programming experience in JavaScript in two different ways. They are quirky to put together, but still worth it.

**Comment by marcusradell** [comment]
Useful tips! I didn't feel immutable contribute enough when using rxjs though since most code was pure to begin with. ConcatAll and other array-based operators needed a toJS/fromJS map-sandwich when using immutable. Anyhow, I think I agree with typescript after reading what you wrote.
