### ISSUE TITLE
How would you convince someone to use Cycle.js over other frameworks?

### ISSUE THREAD

**Issue by marszall87** [staltz/ama#14]
Let's assume that "the other framework" is something with similar feature set, e.g. React or Vue.js.

**Comment by staltz** [comment]
- Among the "big names", Cycle.js is the only framework that separates logic from effects. This enables: swapping effects drivers more easily, testing more easily without any kind of invasive mocking, also makes your application logic more deterministic, more predictable.
- The architecture in Cycle.js always has an answer for "where should I place this code?". 
- The architecture is easily visualizable. If you need to debug something or explain it to a colleague, you can draw the architecture on paper. Drawing it is easy and in some cases can be done even automatically (see the DevTool)
- Streams make some very complex stateful code very easy and short to write, such as complex drag and drop with delays and timeouts, or typeahead http requests.
