### ISSUE TITLE
Do you see any relation between reactive programming and machine learning?

### ISSUE THREAD

**Issue by geovanisouza92** [staltz/ama#17]
Considering TensorFlow, each "tensor" seems to be a simple operation that propagates changes to another tensors, which seems similar (at least from my very superficial perception) to observables. 

What do you think about it and how do you think that functional and reactive programming could help in this field?

**Comment by staltz** [comment]
Yes! I talked about that here https://www.youtube.com/watch?v=1ToJ7cxb1R8&feature=youtu.be&t=897 around 14:55
