### ISSUE TITLE
Any plan to write a tutorial on "How to Author JS Library in Typescript"?

### ISSUE THREAD

**Issue by livingmine** [staltz/ama#18]
The only resource i find on the internet is [https://shellmonger.com/2016/03/11/creating-javascript-libraries-with-typescript-and-webpack/](url). Having more resources for mere mortal to be able to do so might increase the number of JS libraries authored in Typescript. Thanks!

**Comment by staltz** [comment]
I don't plan to write specifically about TypeScript libraries, but I've been writing about authoring libraries in general, like http://staltz.com/api-design-tips-for-libraries.html. I don't know what's so different about authoring a library in TypeScript, all you need to know is how to write TypeScript.
