### ISSUE TITLE
Do you use an error logging service like Sentry or Rollback?

### ISSUE THREAD

**Issue by donaldpipowitch** [staltz/ama#19]
You recently talked about tracking services like Google Analytics ([here](https://twitter.com/andrestaltz/status/808695912407121920)). I wonder what do you think about error logging services like Sentry or Rollback? Do you use one of them. If not, do you have an alternative. If yes, which one and why?

**Comment by staltz** [comment]
I don't use them, sorry. I work mostly with frontend, not so much full-stack.

**Comment by donaldpipowitch** [comment]
Oh, these are for the frontend :) e.g. they can collect stack traces from minified code and map them back to the source code with source maps.

Do you monitor your apps in the wild somehow else?

**Comment by staltz** [comment]
Oh, interesting. thanks :)
