### ISSUE TITLE
Your recommendation on making cognitive shift to declarative/functional style programming

### ISSUE THREAD

**Issue by xxzefgh** [staltz/ama#20]
I'm asking for books/articles/insights or virtually any type of information (besides actually writing code) that you think is important to develop that kind of thinking, specifically intended for imperative/OOP style developers, if it helps to form your answer.
Thanks 😇

**Comment by staltz** [comment]
> (besides actually writing code)

That's how I learned it, but if you're looking for a book, I think one of the nicest is https://drboolean.gitbooks.io/mostly-adequate-guide/content/ 

:)
