### ISSUE TITLE
Fractal system properties

### ISSUE THREAD

**Issue by marcusradell** [staltz/ama#27]
One of the main properties I lack when not using Observables, is the capability of combining substreams into a larger stream that holds the same set of behaviour.

## Examples:
1. In React components, we can do render callbacks to propagate state, but you will probably need to reinvent the combineLatest as a component to get it to be fractal on the state-level.

2. Looking at microservices and Kafka, you usually start with a global event bus, and then you break out rivers that you can subscribe to instead of the main event bus to avoid overloading the main bus. This feels like how Redux does it with a global mindset, where it can be partially fractal, but some properties always stay on the global level.

## Questions
1. Have you seen any trends on where we are headed in the future across the programming domain? Are we getting closer to doing Observable streams everywhere, or maybe fractal systems?

2. Why aren't we discussing system properties more holistically? It seems like cycle.js and other streams-based systems solve lots of pains when it comes to message passing. Why is that not a part of a microservice architecture debate?

## Personal thoughts
To me, it seems like we are ignoring the next big paradigm of fractal systems, still holding on to monolithic systems when we do frontend components and backend microservices, and get bad results. 

To me, it seems like React will unavoidably reinvent observable streams in the near future. Microservices have a higher threshold for combining services, but also a larger need for coordinating. My guess is that we need a micro-event bus with fractal properties.

Kinda complex question here, so if anyone is following this AMA, feel free to pitch in. The floor is open :-)

**Comment by staltz** [comment]
> Have you seen any trends on where we are headed in the future across the programming domain? 

There seems to be a mild inclination towards functional programming, but not fully. 

- - -

I think there is very little to *invent* in programming. Most of the great things we see and use today were invented long time ago, right now we're just massaging those ideas to frame them in convenient APIs. But conceptually, basically all these cool concepts are old, dressed in good-looking clothes:

- Redux: event-sourcing
- Cycle.js: Haskell Stream I/O, Dataflow prog, Hexagonal architecture (ports & adapters), FRP
- Observable: Iterator-inspired, Haskell list inspired, push-based streams
- Message passing: too old to even trace its origin
- CombineLatest: Applicative
- Fractal: Lenses, or in general, functional optics https://github.com/phadej/optika / https://github.com/calmm-js/partial.lenses, or in general, just functional programming with a consistent nested architecture

> Why aren't we discussing system properties more holistically? 

We just haven't woken up to it yet. We need better APIs that show how and where those concepts can shine.

**Comment by marcusradell** [comment]
functional optics seems like the area I need to explore deeper then. Thanks again <3
