### ISSUE TITLE
Why do Observables need "complete"?

### ISSUE THREAD

**Issue by dralletje** [staltz/ama#32]
I hope it's also okay to post "philosophical" questions about Observables here.
I searched the internet but couldn't think of any more "philosophical" programming thinking about observables.

Observables can, right now, emit an "complete" event, when they are not going to emit any value again. It's justified in this video (https://www.youtube.com/watch?v=sTSQlYX5DU0&t=1717s) with the reasoning "We make an observable of peoples qoutes, but people can die, so then they are "completed"". I don't see why it is a vital part of an Observable, however. "alive" or "death" are both states of a person, which would make for a good "personLifeState$".

Why is it, that in all the tutorials I see online, and observable is explicitly not described as "Something that can emit values/change over time", but "Something that can emit values/change of time, **and** can complete too".

In thinking about the relation between observables and signals, and the different kinds of Observables, I sometimes hit a problem I could get around by ditching the necessity of "complete" on observables, so I figured I would need some more knowledge about why we need it :)

**Comment by geovanisouza92** [comment]
I know that this question is not directed to me, but I reply it asking you:
how would you signal the completion of something? If you need to send
events from B$ after A$ events are fully consumed, for example (concat
operator)?

Em ter, 30 de mai de 2017 19:06, Michiel Dral <notifications@github.com>
escreveu:

**Comment by dralletje** [comment]
@geovanisouza92 it's cool, hahaha :-)
I didn't think of concat before, so thanks!
But I think the reason I didn't think of concat, is that I never found a need for concat either 😅 
I'm thinking very hard of something that I would use concat for, but I think I just never get to a case where I have observables that can end, anyway, hehehe.

Then again, if you would know some "state" would cause the observable to not emit anymore, you can get an observable of exactly that state:
You read from "websocketMessages$" until "websocketAlive$" returns false. (although, if your websocket stops without you doing or anticipating so, I would say it's an error, and if you know it should stop, there is apparently some other state that you can base on if you are still expecting messages)

If you can find a good use case for `.concat`, that isn't easily done another way, please tell because I feel very dumb right now, not being able to recite one use case, hehehe.

**Comment by staltz** [comment]
Hi @dralletje, indeed Geovani gave a good hint, that complete is necessary to implement concat. Here is a real world example of concat: 
https://github.com/staltz/matrixmultiplication.xyz/blob/f3b88ff00432f0430bdfb552dcc4edd16e46b3ac/src/Calculator/view/tweens.ts#L82
We need to concatenate one animation after the other.

But in general, it's not just for concat, it's just a way of signalling "you can be sure that this observable won't emit events anymore", which can be used either for concat, or for cleanups (let's say `element.removeEventListener` under the hood, or something like that API). There are several operators in RxJS that depend on the notion of completion. It's important.
