### ISSUE TITLE
Monadic vs Stream based, how does one decide?

### ISSUE THREAD

**Issue by tusharmath** [staltz/ama#34]
I have probably watched your talk here https://www.youtube.com/watch?v=Tkjg179M-Nc over 10 times already and shared it with a lot of people. Its too cool! 

I wanted to understand more about why haskell chose monadic over stream IO. One of the reasons I could think of is sometimes when we have multiple side effects there is a lot of to and fro of messages which is not only very inefficient, it also pollutes the message space causing collisions eventually. Its also really tough to find a suitable name for each message type.

*Here when I say Stream I mean the conventional message based IO and not wrapping a monad inside a stream*

I am really seduced into using a message based architecture because its awfully easier to test but honestly I have never been able to sell it to my colleagues because of the above mentioned issues.

**Comment by staltz** [comment]
Hi @tusharmath :)

Are you building a UI program or a transformational program? The talk makes that distinction and shows how stream I/O is useful for UI programs. That said, monads are so general that they are often useful in larger contexts, not just I/O. For instance, monad transformers and free monads let you go up in abstraction and essentially build DSLs for your problem at hand. Best resource I can remember right now is this: http://degoes.net/articles/modern-fp
