### ISSUE TITLE
Do you think that callbags are related to CSP?

### ISSUE THREAD

**Issue by geovanisouza92** [staltz/ama#37]
In the sense that callbag and CSP have this concept of synchronous message passing, while the process is abstracted away by the event-loop nature of JS engines.

Would be possible to have two callbag "threads" communicating?

**Comment by staltz** [comment]
Both CSP and Callbags have bidirectional communication, so they are in essence similar, but also there is a third model: Actor model. All these three share in common one basic idea: bidirectional message passing, but they differ in details. 

See this wikipedia page https://en.wikipedia.org/wiki/Communicating_sequential_processes and section "Comparison with the actor model".

I'm not super familiar with CSP, but I can note at least some differences:

- Callbags don't "block" or "await" on the channel, while CSP channels do
- CSP has an explicit concept of a channel between the two processes, in callbag you only have the two processes directly sending messages to each other without a channel in between
- Callbags have an initial agreement and a concluding end, I don't think CSP has this
