### ISSUE TITLE
How did you end up in Finland? And what do you think about the Nordics? 

### ISSUE THREAD

**Issue by alexdriaguine** [staltz/ama#40]
My family are also immigrants (from Russia) living in Sweden, I was just curious about your story :)

**Comment by staltz** [comment]
Hi! I prefer to not share *that* much on the internet. I love the Nordics, though, Copenhagen is my favorite city. :)

**Comment by alexdriaguine** [comment]
Oh okay, I respect that choice ☺ I agree Copenhagen is a really nice city!
