### ISSUE TITLE
Where can I find your old tweets?

### ISSUE THREAD

**Issue by hossameldeen** [staltz/ama#41]
Hi there!

Occasionally, I google something and add `andrestaltz` to see your opinion on it. However, I've noticed that some of the links Google gives me for your tweets seem to be broken. Did you delete them on purpose or can I have access to them?

Example: Googling _'andrestaltz json schema'_ gives me [this tweet](https://twitter.com/andrestaltz/status/788743214404661248) but it seems to be broken :(. The result on google is:

> André Staltz on Twitter: "For describing JSON schemas, #TypeScript is ...
> https://twitter.com/andrestaltz/status/788743214404661248
> Oct 19, 2016 - For describing JSON schemas, #TypeScript is actually a compelling and readable alternative to ... André Staltz @andrestaltz 19 Oct 2016.

**Comment by staltz** [comment]
@hossameldeen Hi! Sorry, yes I delete older tweets on purpose. I try to materialize all the "valuable" tweets as blog posts, though.

**Comment by hossameldeen** [comment]
No problem. Were good while they lasted :-)

Thank you. Feel free to close.
