### ISSUE TITLE
What do you think of Svelte?

### ISSUE THREAD

**Issue by cbenz** [staltz/ama#42]
[Svelte](https://svelte.technology/) project produces JavaScript code, so is more a compiler of components than a library, as it does not need to be included at runtime.

What do you think of Svelte, and of this approach?

**Comment by staltz** [comment]
@cbenz I really liked the compilation idea in Svelte, and find it an impressive technical feat to build. Other than that, the development experience and API of the framework itself is  - neither bad nor amazing - basic.
