### ISSUE TITLE
Do you have any suggestions for local mesh networking hardware?

### ISSUE THREAD

**Issue by ml172** [staltz/ama#47]
I was going to ask you about BlockStack after getting pinged back on twitter (I didn't know this AMA existed!), but I see that you've already answered that question. 

In the same vein (mesh network type stuff) I was wondering if you had any insights with respect to hardware for local mesh networks. A lot of what I can find doesn't seem to be general purpose enough. For example, it is limited to something like instant messaging. 

I'm interested in setting up a local wireless network with some friends in my community (distances max around 700 meters). It would be a cool pilot project to get something started - just to see if its possible.

**Comment by staltz** [comment]
Hi! Sorry it took so long to answer (partly because I don't have a good answer to this). The only projects that comes to mind are https://librerouter.org/ and https://althea.org/
