### ISSUE TITLE
What do you about WASM and it's impact on the future of the web?

### ISSUE THREAD

**Issue by michalvankodev** [staltz/ama#6]
Hey, btw: I hope we will meet again at CycleConf ;)

**Comment by staltz** [comment]
I don't have an opinion on WASM. I think it's too early to say something about it, but I think it's an effort in the right direction. The web is definitely the most important programming and distribution environment we have, and it needs to get faster. I like it how WASM does that without becoming yet-another-plugin like Flash or Java Applets. It still maintains core principles that we have with JS, like View Source, etc.
