### ISSUE TITLE
Your relation to Git's problems

### ISSUE THREAD

**Issue by Bloomca** [staltz/ama#7]
Do you like GIT? Or do you think it is just "good enough for the time" tool?

For instance, some things are really cumbersome in GIT, like merging new commits from the branch if you have already comitted your owns (or other similar problems).

Do you think that it should be improved, or good visual tools are enough for that?

Thanks!

**Comment by staltz** [comment]
Git could be better. I used to use Mercurial, it was nice and in some ways more intuitive than Git. On the other hand it's good to have one standard tool for version control, we can get things done without arguing. Overall I agree it could be better, but I'm not passionate about solving this problem. It actually is "good enough".
