### ISSUE TITLE
One recommendation to programmers ?

### ISSUE THREAD

**Issue by cybermaxs** [staltz/ama#8]
Hi, 
If you could write a topic in a book like "97 Things Every Programmer Should Know", what will you say ?
Basically, what is your personnal recommendation for doing our job.

**Comment by staltz** [comment]
Hi. I think two things may help a lot:
- The ability to think in multiple levels of abstraction http://futurice.com/careers/technical-interviews-at-futurice
- Debugging as a process of understanding the runtime behavior thoroughly http://futurice.com/blog/why-debugging-is-all-about-understanding
