### ISSUE TITLE
Mentoring

### ISSUE THREAD

**Issue by nickbalestra** [staltz/ama#9]
I've read you mentoring some engineers and would love to hear from your experience.
If you have to share 1 thing only for "wannabe mentors" and 1 thing only for "wannabe mentored by you", what that would be?

**Comment by staltz** [comment]
The mentoring I was doing was more like private lessons. I do it through codementor.io

> If you have to share 1 thing only for "wannabe mentors" and 1 thing only for "wannabe mentored by you", what that would be?

I'd say give it a try. Become a mentor to learn. Become a mentored to learn.

I noticed how teaching is an excellent way of learning. Sounds like cheating, but what teaching does for learning is that it helps you consolidate concepts that you already know. It helps lift subconscious knowledge to a conscious level. And once you materialize your knowledge in words and diagrams, it helps you re-evaluate and think more objectively about that concept. I got so excited about this process, when once I was preparing slides for a conference talk about Cycle.js, and I noticed something fundamentally new about it, that led me to redesign Cycle.js.
